# Generated by Django 5.0.3 on 2024-04-16 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(blank=True, max_length=50)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('notify_emails', models.BooleanField(default=True)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=True)),
                ('show_activity', models.BooleanField(default=True)),
                ('audio_quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
