# Generated by Django 5.0.3 on 2024-04-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='stage_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.AddField(
            model_name='artist',
            name='Email',
            field=models.EmailField(default='derrric65@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='Password',
            field=models.CharField(default='nakacwa123', max_length=128),
        ),
        migrations.AddField(
            model_name='artist',
            name='Username',
            field=models.CharField(default='eddy', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='Artist_Name',
            field=models.CharField(default='Edrisa Musuza', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='Stage_Name',
            field=models.CharField(default='Eddy Kenzo', max_length=100),
        ),
    ]
