# Generated by Django 5.0.3 on 2024-04-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('song_image', models.ImageField(blank=True, upload_to='song_images/')),
                ('year', models.IntegerField()),
                ('singer', models.CharField(max_length=255)),
                ('song_file', models.FileField(upload_to='song_files/')),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Runyankole', 'Runyankole'), ('English', 'English')], default='Hindi', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
