# Generated by Django 5.0.3 on 2024-04-24 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_alter_music_id_alter_playlist_id_alter_recent_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='song_file',
            field=models.FileField(upload_to='Songs/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='song_image',
            field=models.ImageField(blank=True, upload_to='Songs/'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('notify_emails', models.BooleanField(default=True)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=True)),
                ('show_activity', models.BooleanField(default=True)),
                ('audio_quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
