# Generated by Django 5.0.3 on 2024-04-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0010_mp3file_settings_alter_userprofile_audio_quality_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Local', 'Local'), ('English', 'English')], default='English', max_length=20),
        ),
    ]
