# Generated by Django 5.0.3 on 2024-04-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_uploadedfile_delete_mp3file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='mp3_file',
            field=models.FileField(upload_to='Songs/'),
        ),
    ]
