# Generated by Django 5.1.3 on 2025-04-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0014_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='mp3_file',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='album',
            field=models.CharField(default='Unknown Album', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='language',
            field=models.CharField(choices=[('Local', 'Local'), ('English', 'English')], default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='Unknown Title', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='singer',
            field=models.CharField(default='Unknown Artist', max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='Song/'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='song_img',
            field=models.FileField(blank=True, null=True, upload_to='Song/'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
