# Generated by Django 5.0.3 on 2024-10-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
